package me.never.blockparty;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.EventHandler;import org.bukkit.event.Listener;import org.bukkit.event.player.PlayerQuitEvent;import org.bukkit.plugin.RegisteredServiceProvider;import org.bukkit.scheduler.BukkitTask;import java.util.*;
public final class Game implements Listener{enum State{WAITING,STARTING,PLAYING}final NeverBlockParty p;final Arena a;final LinkedHashSet<UUID> players=new LinkedHashSet<>(),alive=new LinkedHashSet<>();BukkitTask task;State state=State.WAITING;int countdown,round;Material target;final Random random=new Random();Economy economy;
 Game(NeverBlockParty p,Arena a){this.p=p;this.a=a;RegisteredServiceProvider<Economy> rsp=p.getServer().getServicesManager().getRegistration(Economy.class);if(rsp!=null)economy=rsp.getProvider();}
 @EventHandler public void quit(PlayerQuitEvent e){if(players.contains(e.getPlayer().getUniqueId()))leave(e.getPlayer());}
 void join(Player q){int max=p.getConfig().getInt("arena.max-players",16);if(state!=State.WAITING){q.sendMessage("§cA game is already starting or running.");return;}if(players.contains(q.getUniqueId()))return;if(players.size()>=max){q.sendMessage("§cThe Block Party is full.");return;}players.add(q.getUniqueId());q.setGameMode(GameMode.ADVENTURE);q.teleport(a.spawn(players.size()-1,Math.max(1,players.size())));broadcast("§a"+q.getName()+" §7joined §f("+players.size()+"/"+max+")");if(players.size()>=p.getConfig().getInt("arena.min-players",2))start();}
 void leave(Player q){if(!players.remove(q.getUniqueId()))return;alive.remove(q.getUniqueId());if(q.isOnline())returnPlayer(q);if(alive.size()<=1&&state==State.PLAYING)finish();if(players.size()<p.getConfig().getInt("arena.min-players",2)&&state==State.STARTING){cancel();state=State.WAITING;broadcast("§cNot enough players. Countdown cancelled.");}}
 void start(){if(state!=State.WAITING||players.size()<p.getConfig().getInt("arena.min-players",2))return;state=State.STARTING;countdown=p.getConfig().getInt("game.countdown",10);cancel();task=Bukkit.getScheduler().runTaskTimer(p,()->{if(countdown<=0){cancel();begin();return;}broadcast("§eGame starting in §f"+countdown+"§e...");countdown--;},0,20);}
 void begin(){state=State.PLAYING;alive.clear();alive.addAll(players);round=0;int i=0;for(UUID id:alive){Player q=Bukkit.getPlayer(id);if(q!=null){q.setGameMode(GameMode.ADVENTURE);q.teleport(a.spawn(i++,alive.size()));}}nextRound();}
 void nextRound(){if(alive.size()<=1){finish();return;}round++;List<String> n=p.getConfig().getStringList("colors");target=Material.valueOf(n.get(random.nextInt(n.size())));int base=p.getConfig().getInt("game.round-seconds",5),after=p.getConfig().getInt("game.speed-up-after",3);countdown=Math.max(p.getConfig().getInt("game.minimum-round-seconds",1),base-Math.max(0,(round-after)/2));for(UUID id:alive){Player q=Bukkit.getPlayer(id);if(q!=null){String name=target.name().replace("_WOOL","").replace("_"," ");q.sendTitle("§f§l"+name,"§eSTAND ON THIS COLOR!",3,30,5);}}cancel();task=Bukkit.getScheduler().runTaskTimer(p,()->{if(countdown<=0){cancel();collapse();return;}for(UUID id:alive){Player q=Bukkit.getPlayer(id);if(q!=null)q.sendActionBar("§eStand on §f§l"+target.name().replace("_WOOL","").replace("_"," ")+" §e— §f"+countdown+"s");}countdown--;},0,20);}
 void collapse(){a.collapse(target);Bukkit.getScheduler().runTaskLater(p,()->{for(UUID id:new HashSet<>(alive)){Player q=Bukkit.getPlayer(id);if(q==null){alive.remove(id);continue;}if(q.getLocation().getY()<a.y-3||q.getLocation().clone().subtract(0,0.15,0).getBlock().getType()!=target){alive.remove(id);q.sendTitle("§c§lELIMINATED","§7Better luck next round!",3,35,8);q.setGameMode(GameMode.SPECTATOR);}}a.restore();nextRound();},p.getConfig().getLong("game.restore-delay-ticks",20));}
 void finish(){cancel();UUID id=alive.stream().findFirst().orElse(null);if(id!=null){Player q=Bukkit.getPlayer(id);if(q!=null){double money=reward(players.size());if(economy!=null&&money>0)economy.depositPlayer(q,money);q.sendTitle("§6§lWINNER!","§e"+q.getName(),5,60,10);q.sendMessage("§aReward: §2$"+money);}}Bukkit.getScheduler().runTaskLater(p,()->{for(UUID x:players){Player q=Bukkit.getPlayer(x);if(q!=null)returnPlayer(q);}players.clear();alive.clear();a.restore();state=State.WAITING;},60);}
 double reward(int n){if(n<=4)return p.getConfig().getDouble("rewards.2-4",100);if(n<=8)return p.getConfig().getDouble("rewards.5-8",250);if(n<=12)return p.getConfig().getDouble("rewards.9-12",500);return p.getConfig().getDouble("rewards.13-16",1000);}
 void stop(){cancel();for(UUID id:players){Player q=Bukkit.getPlayer(id);if(q!=null)returnPlayer(q);}players.clear();alive.clear();a.restore();state=State.WAITING;}
 void status(Player q){q.sendMessage("§b§lBlock Party §8» §fState: §e"+state+" §7| Players: §f"+players.size()+" §7| Alive: §f"+alive.size());}
 void returnPlayer(Player q){World w=Bukkit.getWorld(p.getConfig().getString("return-world","spawn"));if(w==null)w=Bukkit.getWorlds().get(0);q.setGameMode(GameMode.ADVENTURE);q.teleport(w.getSpawnLocation());}
 void cancel(){if(task!=null){task.cancel();task=null;}}void broadcast(String s){for(UUID id:players){Player q=Bukkit.getPlayer(id);if(q!=null)q.sendMessage("§b§lBlock Party §8» §r"+s);}}
}